version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: freshapi_postgres
    environment:
      POSTGRES_DB: freshapi_db
      POSTGRES_USER: freshapi_user
      POSTGRES_PASSWORD: freshapi_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U freshapi_user -d freshapi_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  adminer:
    image: adminer:latest
    container_name: freshapi_adminer
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: postgres

volumes:
  postgres_data: