[build]
builder = "NIXPACKS"

[deploy]
startCommand = "./scripts/deploy.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { ENVIRONMENT = "production" }

[environments.staging]
variables = { ENVIRONMENT = "staging" }