[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cargo run --release --bin freshapi"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { ENVIRONMENT = "production" }

[environments.staging]
variables = { ENVIRONMENT = "staging" }